DOCS-1627: Update README.md
viam-labs/verification-system pull request #1
Opened 2024-02-02 23:15 UTC by skyleilani

2024-02-09 12:27 UTC, npentrel commented
was going to review but I think @sguequierre has more context

2024-02-21 17:06 UTC, sguequierre requested changes

2024-02-21 17:06 UTC, sguequierre commented on README.md
> +## Next Steps
```suggestion
## Next steps
```

2024-02-21 17:06 UTC, sguequierre commented on README.md
> +
Here it would be good to add an `Example configuration` section like this https://github.com/viam-labs/generator-viam-module/blob/main/generators/app/templates/python/README.md#example-configuration you can set it up on the app to see the module JSON and use example attributes!

Don't think we need to show a full configuration with the detectors

2024-02-21 17:06 UTC, sguequierre commented on README.md
> +Add the alarm logic by following the instructions to [Add the `verification-system` module to your machine](https://docs.viam.com/registry/configure/#add-a-modular-service-from-the-viam-registry).<br
You can just give instructions here instead of pointing to docs. Rework this part to look like https://github.com/viam-labs/generator-viam-module/blob/main/generators/app/templates/python/README.md#configure-your--api_name_lower- Like `Navigate to the **Config** tab of your machine's page in [the Viam app](https://app.viam.com/).
Click on the **Components** subtab and click **Create component**.`

2024-02-21 17:06 UTC, sguequierre commented on README.md
> +## Build and Run
```suggestion
```

2024-02-21 17:06 UTC, sguequierre commented on README.md
> +To use this module, configure your machine with the resources outlined in this readme.
Module is meant to be flexible, don't have to use the configuration from tutorial
Change this section from "Build and run" to "Requirements" (like here https://github.com/viam-labs/generator-viam-module/blob/main/generators/app/templates/python/README.md#requirements) and then list out 
- webcam 
- 2-3 detectors
- transform camera (to see detections)

2024-02-21 17:06 UTC, sguequierre commented on README.md
> +This module implements Viam's machine learning (ML) model service and vision service to provide a tool for facial verification and object detection.
It doesn't implement the ML model service, just can use mlmodel vision services. Module itself is a vision service: `vision / classifier:verification-system`
Change to match template like "This module implements the rdk vision API in a verification-system model."

2024-02-21 17:06 UTC, sguequierre commented on README.md
> +### Configure a facial detector
Don't need this part

2024-02-21 17:06 UTC, sguequierre commented on README.md
> +### Configure an `mlmodel` person detector
Don't need this part but could be helpful to link to docs in requirements

2024-02-21 17:06 UTC, sguequierre commented on README.md
> +#### Attributes
Can delete this

2024-02-21 17:06 UTC, sguequierre commented on README.md
> +
Add build and run section here following template: https://github.com/viam-labs/generator-viam-module/blob/main/generators/app/templates/python/README.md#build-and-run

2024-02-21 17:06 UTC, sguequierre commented on README.md
> +Before configuring the resources for this module, [Create a new machine](https://docs.viam.com/fleet/machines/#add-a-new-machine) in the Viam app. Then [Install `viam-server`](https://docs.viam.com/g
Can remove this and add "create a machine" and "Configure a Machine" notes from template

2024-03-07 21:28 UTC, sguequierre approved these changes
Lgtm % final mostly spacing comments

2024-03-07 21:28 UTC, sguequierre commented on README.md
> +Navigate to the **Config** tab of your machine's page in [the Viam app](https://app.viam.com).Click on the **Services** subtab and click **Create service**. Select the `vision` type, then select the
```suggestion
Navigate to the **Config** tab of your machine's page in [the Viam app](https://app.viam.com).
Click on the **Services** subtab and click **Create service**.
Select the `vision` type, then select the `classifier:verification-system` model.
Enter a name for your vision service and click **Create**.
```
Missing space-- think this should fix

2024-03-07 21:28 UTC, sguequierre commented on README.md
> +  {
```suggestion
```
Don't need this set of parenthesis

2024-03-07 21:28 UTC, sguequierre commented on README.md
> +}
```suggestion
```

2024-03-07 21:28 UTC, sguequierre commented on README.md
> +| `countdown_time_s` | int | Optional | The time in seconds the system will remain in the `COUNTDOWN` state before transitioning to the `ALARM`state.<br/>Default: `20` |
```suggestion
| `countdown_time_s` | int | Optional | The time in seconds the system will remain in the `COUNTDOWN` state before transitioning to the `ALARM`state.<br/> Default: `20` |
```

2024-03-11 18:08 UTC, kharijarrett reviewed
This is looking good! Just one real comment about finishing the state table. Appreciate this work as always!

2024-03-11 18:08 UTC, kharijarrett commented on README.md
> +| `TRIGGER_2` | The secondary detection state. | Detector: `trigger_2_detector`<br/>Labels: `trigger_2_labels`<br/>Confidence: `trigger_2_confidence` | `TRIGGER_1`   |
Need to add the other 3 states to this table: COUNTDOWN, ALARM, and DISARMED. The info is below in the current README

2024-03-11 18:08 UTC, kharijarrett commented on README.md
> +- If you don’t want the `ALARM` capabilities, and would like to just use it as a notification system when a detector gets triggered, set `disable_alarm` to `"true"`, which prevents `TRIGGER_2` from e
I was gonna cry about this being gone but I actually love it here.

2024-03-12 00:35 UTC, skyleilani commented on README.md
> +- If you don’t want the `ALARM` capabilities, and would like to just use it as a notification system when a detector gets triggered, set `disable_alarm` to `"true"`, which prevents `TRIGGER_2` from e
I could see this still being really helpful right below the introduction  since it might be nice to know when they're beginning to configure the module. What do you think though?

2024-04-11 20:02 UTC, merged